/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/singhmeghna79/crd-controller/pkg/apis/dummy/v1alpha1"
	scheme "github.com/singhmeghna79/crd-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FirstCrdsGetter has a method to return a FirstCrdInterface.
// A group's client should implement this interface.
type FirstCrdsGetter interface {
	FirstCrds(namespace string) FirstCrdInterface
}

// FirstCrdInterface has methods to work with FirstCrd resources.
type FirstCrdInterface interface {
	Create(*v1alpha1.FirstCrd) (*v1alpha1.FirstCrd, error)
	Update(*v1alpha1.FirstCrd) (*v1alpha1.FirstCrd, error)
	UpdateStatus(*v1alpha1.FirstCrd) (*v1alpha1.FirstCrd, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FirstCrd, error)
	List(opts v1.ListOptions) (*v1alpha1.FirstCrdList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FirstCrd, err error)
	FirstCrdExpansion
}

// firstCrds implements FirstCrdInterface
type firstCrds struct {
	client rest.Interface
	ns     string
}

// newFirstCrds returns a FirstCrds
func newFirstCrds(c *DummyV1alpha1Client, namespace string) *firstCrds {
	return &firstCrds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the firstCrd, and returns the corresponding firstCrd object, and an error if there is any.
func (c *firstCrds) Get(name string, options v1.GetOptions) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FirstCrds that match those selectors.
func (c *firstCrds) List(opts v1.ListOptions) (result *v1alpha1.FirstCrdList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FirstCrdList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested firstCrds.
func (c *firstCrds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a firstCrd and creates it.  Returns the server's representation of the firstCrd, and an error, if there is any.
func (c *firstCrds) Create(firstCrd *v1alpha1.FirstCrd) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("firstcrds").
		Body(firstCrd).
		Do().
		Into(result)
	return
}

// Update takes the representation of a firstCrd and updates it. Returns the server's representation of the firstCrd, and an error, if there is any.
func (c *firstCrds) Update(firstCrd *v1alpha1.FirstCrd) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(firstCrd.Name).
		Body(firstCrd).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *firstCrds) UpdateStatus(firstCrd *v1alpha1.FirstCrd) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(firstCrd.Name).
		SubResource("status").
		Body(firstCrd).
		Do().
		Into(result)
	return
}

// Delete takes name of the firstCrd and deletes it. Returns an error if one occurs.
func (c *firstCrds) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *firstCrds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched firstCrd.
func (c *firstCrds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("firstcrds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
