apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "firstcrds.dummy.com"
spec:
  group: "dummy.com"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "firstcrds"
    singular: "firstcrd"
    kind: "FirstCrd"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["message"]
          properties:
            message:
              type: "string"
              minimum: 1
